apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -ansible
namespace: cicd

patches:
- path: deployment_autoscaler.yaml
  target:
    kind: HorizontalRunnerAutoscaler
    name: autoscaler
    namespace: cicd
  options:
    allowNameChange: true
- path: deployment_runner.yaml
  target:
    kind: RunnerDeployment
    name: runner-deployment
    namespace: cicd
  options:
    allowNameChange: true

# patchesStrategicMerge:
#   - deployment_autoscaler.yaml
#   - deployment_runner.yaml

# patches:
#   - patch: |-
#       apiVersion: actions.summerwind.dev/v1alpha1
#       kind: HorizontalRunnerAutoscaler
#       metadata:
#         name: autoscaler-ansible
#         namespace: cicd
#       spec:
#         scaleTargetRef:
#           name: runner-deployment-terraform
#   - patch: |-
#       apiVersion: actions.summerwind.dev/v1alpha1
#       kind: RunnerDeployment
#       metadata:
#         name: runner-deployment
#         namespace: cicd
#       spec:
#         template:
#           spec:
#             repository: wilinger/ansible-homelab

