apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/kustomization.yaml

nameSuffix: -ansible

patches:
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: RunnerDeployment
      metadata:
        name: runner-deployment
        namespace: cicd
      spec:
        template:
          spec:
            repository: wilinger/ansible-homelab
