---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-ansible
  namespace: cicd
spec:
  template:
    spec:
      repository: wilinger/ansible-homelab
