---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
spec:
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 0
  maxReplicas: 1
  scaleUpTriggers:
  - githubEvent:
      push:
    amount: 1
    duration: "5m"