---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
  namespace: cicd
spec:
  template:
    spec:
      repository: wilinger/argocd-homelab
      image: willw0176/actions-self-hosted-runner:v1.0.1
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: autoscaler
  # nammespace: autoscaler
spec:
  scaleTargetRef:
    name: runner-deployment
  minReplicas: 0
  maxReplicas: 1
  scaleUpTriggers:
  - githubEvent:
      push:
    amount: 1
    duration: "5m"