apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django

resources:
  - sealed-secrets/sealed-secret-regcred.yaml
  - sealed-secrets/sealed-doppler-secret-token.yaml
  - sealed-secrets/doppler-secret-stg.yaml
  - pg-data-pvc.yaml
  - pg-deployment.yaml
  - pg-service.yaml
  - django-deployment.yaml
  - django-service.yaml
  - django-ingress.yaml

