---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-data-pvc
  labels:
    app: postgres
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi