apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-credentials
  namespace: cicd
spec:
  encryptedData:
    credentials.json: AgCWvU4IWG2Ge+iRDXtGczh3l4Q1DohhWrBVm6/ahLkZudVxMPx4lamaeLELDiFoMqVpqANzhTJ+iE365UcZY7dlNeolfyD0AQWBCMOl+Sq5Fpt750orLHMAXstWX9fcjaBcvIWBXyMfJfEvoVnoWQ5I+ByDse0I5/UhoBjFxLw45sLAD4aQRuRdSA5GE0xYz/Md1l8r5SlWzTPYGUCZCugIkjc1ditkb2QlXlKVSyJ9j3pMdjJlEelNT+vCbiAv23NokMXZ2moBjMq+Rh/y+kGE7jBy6xbW/zg8Tl9CJTL/FrGS5yLgmfn65ixh0DwymBYT3aOXZMjBQgc+qnbBexPE/82+fkhB1wT03jDP93+0apMUZKefVwSyRR3bSjjzvA1CSmPV7t2Z/ARRW+UtuWzXFANCy6tS0PAvgKXj9B+VeSpi/qs1GS7Us5pMZTXMyP5T5vYOGEwFdbPoVO/eGc7icN1jhT/lbAWCugakEdA+ohD8eArq8Lw1VwEIO7+y8eq4qhCZ7nb8Pwlt7EDW8J0RyuHgRrg4WMyPHrTEudvuv/Hf7oWwdba2KnGZvMk77/2Az34Hi7waTrM2DC0pLUxbgfc8OZ/CCVHsuIf5nKCEc6+UqooT5Ins8/oaDPmgBio37JvYKm8qzOLQ+JQotYJI4F1sEZtlphZqFlV2wJwwX3skTvbBqNdclHIAVGGRnyLlAQib7B2oC3aVp9mLf2O8lPvUfmMQovVBZXVZg+sdpaOkxd1PWtBHyp6nOVjk5EnuRbg8RcNI/svrNir5+VV5SKmtmjBlpeggp6iePH27CQ7J19ni673tEt+asQVpeTF3wy2vgzQYTEu1Rujr4c5gdR2nOws7okwDGMuFefsJwK7N+/deA/7hwP7PXZCrPchBsDTbu78cAtmBmBKFfIp/V/297F2JtdMNWQ/BYsnnsVwEDW+qWlG87Cp0
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-credentials
      namespace: cicd
    type: Opaque

