apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-credentials
  namespace: cicd
spec:
  encryptedData:
    credentials.json: AgCZuvNn7L0lDnmmEx0DLpsfjtNqpMagE5dVWyQnUo8SgGu8oqdds/SL3mFdZQ7ymeajhZ5fgzHfGu6W/52LNcfZgu1bjvts85RMC3+B3baJeDCVKQt0CsvLE3e6FKgWhV+/iF9oJzVQIdELTtwQ2X+bScqtTxb7bOhrC2D4mNTUUs1HBvweTQJ6DaGurJqeLFoi48dq+lxDYxIqzYxGo8O/EODrsK4AqIJszuxyDnz0CHfVQIRmvbzeZrWQoBtoi0kU5uetxxIFSVg29UVMTCM4HmkYr3zgI/ftGXJa2PN69t4DW9mWKEPvBw0Zg7UuebnOTGvMJ4PgLmTqN2AL7tDdvN8xmWrwhtO6LCwXYVeHHpWDUkoEzWcZK7DA3fOAQUgHLX4cfhkj/DjJVJO1ICMB2vffx2fNdZBy7IYr1pmdT4ZLIIT8jr7yCJ2ugNFsxP36cFpPpBinf7lsI+YmwvAtbGq8yqcrUFSD1O2vtut9O/Bq9ElxCjkxIN27AXaGFsxKv2lp+oRC2OvJtM4+MOVrPGr2YZ5WGBKXP8GocS5HJFf8OxPgtost5z/dti63AkNrC/I+5TROTdG8IRrdBY9blszOkXg1750BPQwBQSscO9dmMhjj2dx8gk184QHkvpGNWb28J6EjpQlbNbhuX1gww9daFR1yz5r1iUIT0xYCDOXdSSfmz8UIL4DA7MHciLiJCjbPlWcjHcJ+zdT+IK8EILuxF8x3/7LF316ZF+tBGno5eYU/gFAEPBjHTxnr0JFQpxJNrYlO0/0urW4XpyD0xNTqnCZomrdIUO2p9y5u2WA43Z+KiS8UB4ZQWU5ybOo5Mp1pjaZQT+cAFdFEnts7RGIa8ySI9E5hctmXgJypqiN97q3kKxWxjOZJ+R7vMoHbuLrhBo9y1GwyOXnnHScNHielzZPMmb1hhZWnxAmu17ZR5h8s6WZwEUrL
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-credentials
      namespace: cicd
    type: Opaque

