apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-credentials
  namespace: cicd
spec:
  encryptedData:
    credentials.json: AgAs7uY/d2YuE7lWM9AEDp57TXqX/EnqdaytOhNt6iCfaffds3XJImb+IpWWicXA01c2gJmf+Z1B/vpxvXQ4SmlL5BumMsK4sjr8pKTjQteLV8sq/O1NO9yV2L+jGwneB2N+TiOfQ6aXVB1895QRPYMopVPG13sFQdhrPR1VG1xxFCnzkbTSG32b/0dXKQWW1stGPAI43OQnnYzUK7E7/fiEsCfn5ovbMg3vCFin1gQbedravVE2aAZ2wb6S4mFhJpElXF+LrxmjilvJiEnSXJ/IAOuqUBeY1HQnyhEeXggbhjT0/YYkCfpf5M3GYmoWtBZZrtNYV60Vrc63CjSF8qmYVxH93q34oAG23YYb+b+90djnFmSiLatfJ1iH5Nn5HS4v7Wnqw15CN1F27Iq/l1elDzhnKxADZRvUJ/Jcr0DATBuF/xBUxIKtccCapUdHladx6oU7kd1ItBXw9lO2bgDklsid43bTYIdeCpDxbDeo7EIoZlEr3dmsOeA3vC5nLfDORkCAYGWFSUpLtKw2LSN5f3pdIj1EkV93+3yzLoIK88Y2a54sKWPikBG24rOFkKsFpd42v5bZAlC8s9T33HMCgUdJ3urQhxER/xKO6y7eea5wrqOTsIBuymGyEH9QrlsxRkBrPrgmUNYMbQ8AKDA2PGBJ/V6TRGqzvpXikvbTOhqQWto9XSIHyDw26GT5yfhMVDrcOHaRpCSyotgmLHOQdUxGoG+8Q1WKmMrzLi+C8G4qp7md8eYXao0Rof/+PfZVQNTfj5JpCWgABa1DbO11F4cUCRVL48I/+r9qB3GeXApS+MXokgMA5EcKUcba644AI5Z1IU4jqEEBZ+EbJyYmjCZrF+njFS9x61qNCsMWv+UdtgR4S36BiYqSeX655XDG2yo/O2xAnzt/Iaex1OuAov0Hng+gLg4a0m6/dg0lG2mMbN/Ho5TJzsnT
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-credentials
      namespace: cicd
    type: Opaque

