apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-config
  namespace: cicd
spec:
  encryptedData:
    config.yaml: AgBnhxytpbGroKlWvTXzjBaIsJ4r2jLPNQWAtWYlZ4r+sindLZ+Kd6SE/M1RAgnl2oCPsVZL19C7PIFUTU2vKZSYXyTPbweaVuTXd1JfHec5JYWzk/Tf7M0l3iTmGeuug3fmWKZE/qPl/b9io6fMXF5OqRwQr7qqb1WBjX36T4zJDDlatB1mafxGPSXViFJhNqTAbLraDKKpBtfuMZlgNJBL3cpZKwbKSWPUDk98cDZCJE413WXTS9Jir1X92XcSIG3HYLbFxg6BNhIlAMyBVzqGGpcOTORA/pQoA4jppLPKL0Abo4bUW/XBz4k5a+k95paHp6Xo9X0rvnmknFonUoLOMpP63Cwb+m5maJLsRBK7m1fgPfiQLNMdvccU+wLM4Y1zNHbV2CGQowwj/UZ6vRxuC0KxzFB4qXVqIEjJnB4f7mmOnsrE7LyT++kAzROO7sfdsTNCJHHML/+5zZIVPYMtH397DDL6SoDLViDnYJEOaJkrXwVYLc0GgcNFVeeYg96ja+MGVJfLje2OhYzyBCaUSVeIisQ24EZ97mKROIsPk6XrijP1id5hQB7ePI3OPKmnyU42dhMfvOizy+AE8nASsSs9UFJhLKSDD/j9EPzx59DEojXm0tgsOWJUyheAUktDLZ0iNL3OeCUkPUhU/B4odmkRHA90OQK3B9ItZM5Wi2qhwzAED7eVW7/qVeLgONXob52/X6eLIPECu7FNb81/aNiFb4GILPqjkxMS6tc3gopuMRYY572fTD4KLXKskDiS6UwOZ4jtFm2fkVnGsQKAnLnPcIzktFASwxy08yZWl7v8qdibuFgtpSAmfp+pM/ezk9+Jz8UpfXhmxjTco0npXZnsdtqXJcTztgbQMCP8PyMhzc0+SP4W1B2NtBdSh65FlJxkf6uRc6E43oTAbYwz+hG3mEyD2vFxwU6E7YY0zbqNEKvNg7elsfKAq+iE8UL7hhdYo4AkdbFywxH2PW4U9yCeKBjO7GCt97FlE9TWwqAZKzn/j0ewPHQTvvrJmM+g7Krxi0B5OJi8wKXDAvgt+KWhuBtmXvKuMpIfUf/1DxhwdX+8OG09e/YCp8+YUEUsHdSr9QSYLRAsPLMCQYOVfH3YkWjDfhVH5MUa1CuvxIjzpOjf4GE0F90FLt6x
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-config
      namespace: cicd
    type: Opaque

