apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-config
  namespace: cicd
spec:
  encryptedData:
    config.yml: AgAfBViOfHfZlNIWWHAj7OYbgcYnGOrR+8rPRHi0HIs1QKMDjyPXMsxYy5y7ooVifBb5noltNCUZzmobWbsNiam+kVpEfMwOCM/JFoYVP8HmWYqhUPEuxDqfTWKGX78HqhBggVw4BAdoyRvQC35N2N4l/gVGhsQV6NzHtcohuQRoFdJiB/DsZ/tiFNAKb4Yeonb3bZ40OEYEBOx8V5zjTyKoEHDGqd462HCM5oUJAVcBXdsHKiDIjZ/DoFrksHE76U2zjZlmTL7eHpBY1nRIn8Tbh8E/tqedkaCWhoHIBgedemi2w4gXXMONec+kPu+j1OlvRsoA5NzeUPH1jAMN+FRLhnsQ3ZmpVxwWL/sXeX+ilAa/ymnbJgXHe+FDUvUHlxve9KINmWd+S2HdYXQYOM0vHoyKuXaGcyCtrmNdJti2AYIOURHzxudFAH7kD4JUkAumm3sHkjpvZMfgK7dklARjGhRBYX8GN+BEa2sSzQtXAmQJ/sDoaDKI8sPL2l/tZkcDiFqOEzRDJNux9IUgMOAD6U7FSIOA3GBP8eToTq4xKvGe2lN7weralHRQ1BDWu5JHOV1Qcm5lCPVWzeu7QIhudsQS3cNzlPJT/5g5DMRXFkhnuiA25PF21BtGw3W39cCH88j2ZWhQ1I2k2f2gpyvMKuhLRbKpJVp8zVkyc60fvOLGR9vKflZYps1ri1Rs5Oba/xDKpar/GrSEvQcmfv8zhKsV9tWLDgz01xcbwK8TiFmJu3lP/pixlBFZ3ggMzDKJ1IgWVdYJpvkByAgOFbC7VJAha/DxYtjIHDBCCEzp96iI0eyVjVQ+TL1VtJ561rwy0YDJQ0YqGihctb/ESzH9YPNEWkvj/ZRg49774tK5EHk11iOphlQHJovOGnLdoxPwV+YKBA4wfHyJq48R0SCd9/cyCBaJA9TjryzUWxTBdx1+h390PzJfNL5XIYHBY4CJWTwtrtkDSI59lqNoIJb0ldD/sn3GYZCwNOuAz4KASkxz0LPu7k5RzUVwsV8PV7mFSuRyPO1bLMNRqIXZAjB1y6ZfbAN5p1nJnXFDk+qmTouRrLTc9gQ9CsoXzDoIUyD+FQM/Y2pfutBNRHSDnDY9VloYEeiYEGnoBEWgZD7jRWb0ceQnfpEqbKvWAueO
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-config
      namespace: cicd
    type: Opaque

