apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-config
  namespace: cicd
spec:
  encryptedData:
    config.yaml: AgB7k7eIjntfPhFPmSqqIYrRAo947ib++PngRDVD7AMWxfjLklC2KN2i13Sg9ee4+ENou4IFHdQjkXEKp4Yx+g02T+06d/lQhJda6Q3MqcWjrJ1NKHAXBMVV4OkEuUSFbV56RRx58eBEkyz7HyedZSTsmYG+2XEoGI4Q5vEA7RCEAdHRS7mOrWW/cTsT4Lqle8AyB74dlZPvRl+P9O5juosNXSamHolPcGhW7n8dx8S6uGVux6pGns18neJr7nCZugiDZ+1LYxz4nMVm81pVqwCR0joNqYcsIX4TFUWVe3RBDBPEziUQHDu9odfupOtnmZAcfrTEZPCflIzMX9EY0u8wCYO87qI7xe8xvqUk9/Lpy1pTtxM4dd5bWiugJv4L7zukn/HDhkr+fpodrFdpixv5xrJELbudbgg9yUMbmJtMkNl9QW+gvGzTIpxkn8nvGeekwQcFM5xoSKmv1KHe/xgcvAHwzRzGbn6+NWi0E2TEJ3TZwPm5DxBVlgJ2adNWeXZUtG6IsZ/aOe/MgldEui3gI7l/mSTTE/bgE8Tap6ysOwx5RiKkxBYyBGZZE39cirYC7JHbC5itfuX7gvDKWsN/UWECXLjJXMiC0JSRblJvYfzv5/uv0kvfP9Mv3GINVGvtYFmaG+HMNC1/6QQT9ER7uFl4JNq0teQb1j8/jwI5zUMnq/h02TiwF7Djp/k7ZvIaKMj+V7krvWh9aW6Z4pRNKZxLyAja+UZ49Dlcfe7oDYHT5IZOzzMW3UQ8nxCu8smN7R010E7AE4kuVJn+A4NJoaDp6Xa9vZLuKn+cMgvkChBTWP/Ha+pGL0useHPMUw7jSXIi6YX6e8dLFliCHtg/2i4SgfCM63/WU0Nbk6aXLKy8Ab1KWVbipDWabZ225utn7klvCFJvswixtNV3dUDXUJEqguV6+3Z74YlAXntgKlyn8UYhBgsImukxUTHQ+5mslszVoVsXcndT6WxKdiDW0XScOH11V9WBcgza0ichhCOGGZyQ9Tbhb0sIZ3gntlQaA3eq140qDC2LQEa6ejV2o1ZJ9dqOUGfrXqKbPpQODm0lc40eh2fBzxnHGVQtq5A7XqionQM7jnfMLeUsX0+Qiv0VY0NTagOVugfyPAv85FVTD/dpZAYZiasu98qz
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-config
      namespace: cicd
    type: Opaque

