apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-config
  namespace: cicd
spec:
  encryptedData:
    config.yml: AgBQt/0mqijp86r87KZKJ/3hpRFM2H+2fO1RVgnP5rcBFBgxEfSGnT3BH1tPX9Dn7PP96dnfuQYebrmyT6rJ1Vwx7elXSjsUzj9424MZd/cn8TaJOSsinKZqJo/3u5qJmXTUn8l/LC5B6tZ17S+vI+nQw89muejv10VmytjQ+xFoGgLFcVbTzdNUekHE6U4xPDVTZ1jsqsG//yNKzLzOt2rgPgH9FPA+sVCqYLb7AEI9ffjZTBwn/4rDNZsPUxEHTazAnnBTUp3j2lNYfjpiKCWcU9IgBASBBXBOzRzX0VELMaU2FaLNcxyDigNZbdPLzGexlmzD7p2HHNKGtJcIxUN0BUXX8G6jBLhxnQzMFcl6v/oC4d2ibeqo5N2KR1QciniFWKbY1u9R/kRGDg0E39SylQWJAjlD0j4UTQ0b5iSlUT7k6lB0nSoNmKjAp8cxlyqSndm1bWzCTxotGKHChtnSjEDKT5eoKSbv4rEtDduKCn3cNzZ80puTOvZRf1IpTI0t8gexXnq9RviSqbpe0r4KpeZJox+6LcZrjKfLSEbj+Q+I2FR6RQ6XxFXhtknv22whJBzO/LXTetTpZMNs0otaLpLOSudiki+MZ/z13vAWg9dVnBup3xO9jjpcRYioKW0Sz1rWIP4QkhxEzGuTOhxFyfNOjMhCuLVz90+vlWsgvNIjXFykm62Lhn+oi9D73xiJvHN9R+gH8IE35FGXLdYizYsIsB0ZqwsPmCOHZ9QzD/DeSBue9epWsmzLGKUHuUTcYR0Km59j0zk3gMqjO7aFwleQN5voMzXh9npe+QXH4eZRqKZ0u0laQB3Q/uD+xUGlgJIcJiJBHUvnbCrk8t+TZ7ILfVu1XnxB2MDas2xfzP55sOqWC5qJk2DuppMf9ziINGbhg6HCFRHh+8DsdRgB/Gwp3s7KSRKmegyQmXuFPiB3tdZgTHOwzQu1m0eREb/IVrCMbISBEXh47bgeMaYYnpowDhubzRobL+NicZoedK1N9G841YLNBJadLYt/lOGiS4NxoeeEeeLLYw353amSR+Dh6eM+RhDrR1mT3C6eqcVDKCdoIXTzanC5VfkAP/YsYOP1MGR9rEn/edx0pDSsFtY2oNhe/UYpdRzO7zWriNv9kmoaiqQvnbs2dIzPsOHSMmZ9Tt+m0VfE1OzloLcKli3L9IUuCvyWsdj1dUjsnEt3lArkpbEWrM611C/h3s33t0IUTc/MhlVG8GRIhlc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-config
      namespace: cicd
    type: Opaque

