apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-tunnel-credentials
  namespace: cicd
spec:
  encryptedData:
    credentials.json: AgAhdEQ9ud+637A/gnSMWZGcMCVB/NK5C7P6NebHa5V9daTLXBdb9HMqfdeUENpVinT1BESbg2LAOQ49P4XQBdtZsEXxB8XhiWvUu7pi5o3lU2hpCFEkTmYt3KtSXqZdEhqI35ppKa6h2o329vnY+c+T7YJexY9h6i3JJD/hA9h+IqiRqYgObZFrBthwsOLPMuJuAx9UKE+wZzfv5Pp0qsdUji/pxnk40zgoFkd0Yjjhvc8h5ILNnSmz8+KC61+vD7fmQV5Cd0Yka/evkQA7reSiF14E1i9KVPAFC8y86nAvizYFHxCC3nuQfrBYs/gOR6X1oWpX//HyFTCUXG9thdBpLbZDIt999DZobyzPZKhSb+6XK6310HNdxHNqESehd/l4bI5STWsKbWOvK/w25M1E2ExPRGD4nsOIOdCG0YDMzjpnsojXWhchXclXxMYnObyOjKEssqsftspmu0xrYsy0JfJj1Qi4ylFgy5wR8cLEFp4zOeZeY1MiznSoOqiQp3H6KCSD3Ai95p90zp0FXfsHBzOc7w6oho24a7iJ/nJ+JlcVk5OsMe41DEaap6UWa4HX+doYh2ugMD20ujyNKXAgPJrxhZwX5ug2WUKlXPi6zdk4CZekO79JyJDyFqG6w5kG/h9U/MTR654Bzqy5I1Aok9qCpBFqaYZ0GZMh7BWEIrVKk6qMKdmxBaYaAPXOyEAVpJ6QWgptnPfBj3vf1jUwENYCSi5QQpo6U9iytf1ZC/685tJr0ajK19Ih2JDsaTmpJjYk+PfE1qpOjYkfM38xf0DO7DXk41hIbWeYCfN03kJyJELsP7ZAOcax5iwRhPOf53VD+iY5lxiMd1kFzy1Yf1UpeeOe/ZX7fIeLU1B7X4uHtCLQNObQ73G+s+c3V9Zo2TK0N19fKa3reyVaKsY5ZKkAZ2yWVPOIG+osQgR3a8sBgX+HC8Lu/ER3
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-tunnel-credentials
      namespace: cicd
    type: Opaque

