apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runners
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  project: default
  source:
    path: kustomize/apps/
    repoURL: https://github.com/wilinger/argocd-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
