apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-deployment-django
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  project: default
  source:
    path: kustomize/self-hosted-runners/overlays/django
    repoURL: https://github.com/wilinger/django-htmx-app-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
