apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-deployment-bpmdb
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  project: default 
  source:
    path: kustomize/self-hosted-runners/overlays/bpmdb
    repoURL: https://github.com/wilinger/argocd-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
