apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-deployment-ansible
  namespace: cicd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  project: default
  source:
    path: kustomize/overlays/ansible
    repoURL: https://github.com/wilinger/argocd-zencluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true