---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cicd
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2022.1.2
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          volumeMounts:
            - name: cloudflared
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared
          projected:
            sources:
            - secret:
                name: argo-tunnel-credentials
            - secret:
                name: argo-tunnel-cert
            - configMap:
                name: cloudflared
                items:
                  - key: config.yaml
                    path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cicd
data:
  config.yaml: |
    tunnel: zencluster
    credentials-file: /etc/cloudflared/credentials.json
    no-autoupdate: true
    ingress:
      - hostname: argocd-ext.zencluster.org
        service: https://argocd.zencluster.org
      - hostname: githooks.zencluster.org
        service: http://actions-runner-controller-webhook.cicd.svc.cluster.local:80
      - hostname: sq.zencluster.org
        service: https://sq.zencluster.org
      - service: http_status:404