apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/actions-runner-controller
    repoURL: 'https://github.com/wilinger/argocd-zencluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets+gpg-import-kubernetes://argocd/helm-secrets-private-keys#key.asc?secrets.yaml
  project: infra-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
