apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  finalizer:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: infra-apps
  source:
    path: infra-apps/
    repoURL: https://github.com/wilinger/argocd-homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
