apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: security
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/vault
    repoURL: 'https://github.com/wilinger/argocd-zencluster.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: infra-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


