---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment-argocd
  namespace: cicd
spec:
  template:
    spec:
      repository: wilinger/argocd-homelab
