apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: cicd
spec:
  destination:
    namespace: cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/cloudflared
    repoURL: 'https://github.com/wilinger/argocd-homelab.git'
    targetRevision: HEAD
  project: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
