apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    namespace: cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/harbor
    repoURL: 'https://github.com/wilinger/argocd-homelab.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - secrets+gpg-import-kubernetes://argocd/helm-secrets-private-keys#key.asc?secrets.yaml
  project: infra-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
