apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: security
    server: 'https://kubernetes.default.svc'
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.0.2
    helm:
      releaseName: sealed-secrets
  project: default
