actions-runner-controller:
  githubWebhookServer:
    enabled: true
    replicaCount: 1
    syncPeriod: 10m
    secret:
      create: true
      name: "github-webhook-server"
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
    service:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: http
          protocol: TCP
          name: http
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: githooks.zencluster.org
          paths: []
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
    podDisruptionBudget:
      enabled: false
      # minAvailable: 1
      # maxUnavailable: 3