apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -django
namespace: cicd

patches:
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: HorizontalRunnerAutoscaler
      metadata:
        name: autoscaler
      spec:
        scaleTargetRef:
          name: runner-deployment-django
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: RunnerDeployment
      metadata:
        name: runner-deployment
        namespace: cicd
      spec:
        template:
          spec:
            repository: wilinger/django-htmx-app-demo

