---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: bpmdb-doppler-secrets-stg
  namespace: bpmdb
spec:
  tokenSecret:
    name: bpmdb-doppler-token
  managedSecret:
    name: bpmdb-secrets-stg
    namespace: bpmdb