apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: bpmdb
spec:
  encryptedData:
    .dockerconfigjson: AgA/t2nJauZ3P7JEkhOX2svpE2CtFGxMycsjD4h1GGFJyDZEHywQmv+xfmSHFWbZiRx03xlZ/RYzXZBz9veJaIMCsJv9cQfulSVBKT7/JTpXhdd+H4FhX9GLgcMi7wGc9qiZQfky9ItdTR0jus3W13kvrYR3wWiH2TQMbT51xBoebTAtR9dal/s+1yD5zNUBLZVx4Dc+Vh22sXXTbHX8EE8WjoMjFYOo4QAw5hP5MpUiZ+dwAw/oq/j1HkXokbB1YtaCrpAIO1hx6stV1UlImZU3Y44nwhiPCCrSnFk93NSDXXR0u+mMTjLW/aEPucGfrW16LNAobt54rLH3Da5i9Ydw1hEBzYnqDEWanqx7RYy0zXMhHU331XEaLn+f3iGWbDA1FUyd029JDTnAIGVC8QMAt2XxDWLnvvAyGbGREQ4cECujTOO0r98ol2SjPtXJA+5X7iuxjzB4h3pJIS/05meK8cQvycvIu71vb8Ld6LFGvTrqTLQtE+8NT8SvyOBNoK1S0ZRKerXZ10C+FN7tIQILCMCYTMbSeSiKGCQJwje77Y6GfKekzoaAetP9Jl3bLLoiAVI7RiVsjAXNmTwajYal/4s4xOCH+qS3vs/fknkZgN72BZe80RpUjmRoefKriei4BI/o6Cwgye7lhab35LiLhu3NwbDbYyu6fCe4Ds9H7AA+nt03Cf9aTLdUsxunmNeyoBqU3RFTbkKTW0kI3zanlgAjSHRmPOi5szfrrLkvx6+JkuPOhzx80pq9I1mvXaAHD0xex5yRS0n96eWA0TEvtGjxNWguimhsfReMDaa92qVyEaYsC+LX2SI0HTlDoP0p1IXAQ0TGdrLvG7Zz01yVXnpRjClG8hZ6GJ9X38G3N5rT7uLoeu0Ls0kySHjiJ5Tz66bfZnk=
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: bpmdb
    type: kubernetes.io/dockerconfigjson