apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: regcred
  namespace: bpmdb
spec:
  encryptedData:
    .dockerconfigjson: AgClPylgsJPT4zhAnGKGtsMgaLG8UgIyy92sxdXIAhEMo3HzKfOe09ohDehNW289tfPm1tCDvjfdCieaJgX641VmQj1l9gMa6F7sQvzV2ijOe6uinFGqjTd+9TfX2Qx9OuhK3bEKMXlUi4rHR6hDBMEO4A60pY4ilHuFtAFYaDujoD2VGR2d81laYFGpJLUy7/WZ71KQz9kTSEZWC015E5OOgEIHCPsfKOSzVP+v4R7xODf8MQ0NjwqJ21lEsnzeWepFCJMPtTND0gQrsS4EJIc7VqBz5wnun7i9ZAQeJTZylJDS1iYi0R+bugy5PwHXQb2EeeLOt7XKsmLqn90dfpS/IIPtpiq5uITinpZTIrcHTLPKU14hhelXKkCZLqvP9OR8UJg016b/fwF6evGYHq252ncvtzoPKE9NLdn4gOZUbudOPs3yvmnwDAoz9WIfB/ZU7xTW9Aqw0xrdGANSGsOcXGWKFCIGpGzAOzn2E5bhJIYrPD74yyAqCI8A2pY5ooSOEnvGi7f4teDjy+l+oZZP2sQ28vVv3u+lG2OaDinFVi2mHEmenYogkoWadqPebvax/l10lJ9t4DPxpZgFSzcwqmK2b0Yh50Jvn3F/qIo95FuxEMJUX4pB6NcRiRaYnnuRuG9KbEYKs+8T17Zj1iUwG25WPv3pPr7BA3pvNh1nqtAhzGWvQd0amCtQalqpVM1xzvmX8LSCpObc17hLBgmR2ZpDpvM+gm/U2fN7JAvrQijtFIDQG0v+EqTjTtv1CICxJCisIHhGUFcCbUwt+Jb73u021lwkS8MtpoV8qZPqz+benSF3pmzfFuztQTTEj2rlz6VLI9jV7f/l8hA4vHhi+y+0Rk3rY/xoV3+uOZR0UnEk3QG/40mHRe6gidioXagvmDzzywE=
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: regcred
      namespace: bpmdb
    type: kubernetes.io/dockerconfigjson

