---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cicd
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2022.1.2
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          volumeMounts:
            - name: cloudflared
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: cloudflared
          projected:
            sources:
            - secret:
                name: argo-tunnel-credentials
            - secret:
                name: argo-tunnel-cert
            - secret:
                name: argo-tunnel-config