apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd

resources:
  - deployment.yaml

configurations:
  - sealed-secrets/sealed-secret-credentials.yaml
  - sealed-secrets/sealed-secret-cert.yaml
  - sealed-secrets/sealed-secret-config.yaml

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    
secretGenerator:
  - name: argo-tunnel-credentials
    type: Opaque
    # kustomize build . to generate initial Secrets then delete
    # files:
    # - secrets/credentials.json
  - name: argo-tunnel-cert
    type: Opaque
    # files:
    # - secrets/cert.pem
  - name: argo-tunnel-config
    type: Opaque
    # files:
    # - secrets/config.yml