apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: doppler-token-secret
  namespace: doppler-operator-system
spec:
  encryptedData:
    serviceToken: AgCAf1ISWoJTSJocoEp7/aSoL1yK5HmNWvl6BjiHWe7LqnRCvlA/hDPl28w7AVZF7ru7IQZOVFjnXPBTa9gKmWCPwORkt+Bs3m3BcT3XN34TSawjdjGEiSmsik6T8XHgSsZgz6wcnJ5nfNNyLfhUc7KV/D9zzXOxMR6MpOdXqJ/5IUKJHp1UfpJcyXPlxbXKvKqdbXKdPgTh+wr7hOjat5enZQ81U2H5vnkbBuc64QGlRfRAuTw3wK394ljxpGJ+Q44p4YYJcXcgGj031tuYAex70DJbR9NjLk7Ov33DuOfl3o45Nz5630I20v1NtCcNWVvJUQci/sXvRbDsQHZ+TiNiZ3XIuZ6RVhBhj+5PpKsEY18hv/4XVTkAuVD3ZRCvXLUto0kKOnXVDdGPF1sKQJUCY72Z7wk5afdhesDiv5adC8uWFjM+UwBvJBrshqUGu+HSBPK+StgtpNfB6WaP2jbUb5spjo0qVGttCzgHbogtdKe7nm0a7zOmwWpbMVx8GXEGGRi7ec/RB4A0phuDDyJNPwKBTOqrLwuRDV/5xZ1/dReZ2mpd18jeYyC+mJeP0QV3NZPsdHswh5Ly31axaSBrkZ2ayT5q5U9Rmu5W0ktLava+7Kf1oV7Aqyq7zcuud/+1KkyNa4y/4E3dCcDqkDU7VC+oURVyXdHULxvMKBYfCB6z4yK+Jkpz0HfVC1/jXWLr0C+xS1SYbDZ84SFV4D0I4LAt0dCQ4ekLjDch3mYO+u8gSeQDuxh+NBBlrFVzyklWg0cTuw==
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: doppler-token-secret
      namespace: doppler-operator-system
    type: Opaque

