apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: doppler-token-secret
  namespace: doppler-operator-system
spec:
  encryptedData:
    serviceToken: AgC4TlQuwyS3Wl7PgYS4k2Et6x2huiV3eLVBjh2rBSjubEddNlGUJtofHY6PO4J0ervjx8z67SPXsZJE740zTBzQXfig7ahXeH53uZooGeXTUayAbCnYQHnRDURUofe4kH9E/BebxJsgBPoUsQE1J+Lhzkz5P7K8kcsYGSUBXszWSRVsxTiSUYLKP7J4Oh50r5zX2GBnzlLtVypU/zFdA470KIfJTn6jpEh5QYODa1ylQdyicVPbyVOpwDgQewM9aq0JAxSgL53BCBFfBJklQTMbYKuH/2lC79AdUb3EdOd/U1+O6t7tag0P+r2zAt91JKpuuyclVjG+jmerxblD1/RH1sKJyQk10J2W5UbtxdA/uAxK9X9brUT0NhpSpxwSPWy2fo3e74FifChJIROdMxxDCKy30Cae2AcFglWvlVHAMZDZT7OEodODcOzpmNbKwqk1RKWKKqeVMqYXzVBseVxWBcTB4d0zpb1PH5BYDO8p9CjmykQJCwHWISSvZ1c1euanWU3yh2n1rDKiMKq9jA+tYjJwzS2SQbimypJG2Ywpp55fehQITrXZ3nOCTdQpPidnpxcrXd3y9QtunLeaSOeHDVDzmykt7QCEJqJOP2OKN6wrMfNgnu0q85cnjnMA+QlfD5kqs4XxwdKKRHXkBHsvyMpHepeuvTUtw9XJCMRWsg/LkbqIbYJzIZCSzxrS58gNbVwgpXEg2WdP5UfY0aF0JPn+4reMFzM+hK/Kv4pqbT/2ynJKpbCUaEE7eANxzlc36TQOoQ==
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: doppler-token-secret
      namespace: doppler-operator-system
    type: Opaque