apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -bpmdb
namespace: cicd

### working###
# patches:
# - path: deployment_autoscaler.yaml
#   target:
#     kind: HorizontalRunnerAutoscaler
#     name: autoscaler
#   options:
#     allowNameChange: true
# - path: deployment_runner.yaml
#   target:
#     kind: RunnerDeployment
#     name: runner-deployment
#   options:
#     allowNameChange: true

patches:
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: HorizontalRunnerAutoscaler
      metadata:
        name: autoscaler
      spec:
        scaleTargetRef:
          name: runner-deployment-bpmdb
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: RunnerDeployment
      metadata:
        name: runner-deployment
        namespace: cicd
      spec:
        template:
          spec:
            repository: wilinger/old_bpmdb
