---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmdb
  namespace: bpmdb
  labels:
    app: bpmdb
spec:
  selector:
    matchLabels:
      app: bpmdb
  replicas: 1
  template:
    metadata:
      labels:
        app: bpmdb
    spec:
      initContainers:
        - name: check-pg-ready
          image: postgres:14.2
          command: ['sh', '-c', 
            'until pg_isready -h pg-service -U $POSTGRES_USER -p 5432; 
            do echo waiting for database; sleep 2; done;']
          envFrom:
            - secretRef:
                name: bpmdb-secrets-stg
      containers:
        - name: bpmdb
          image: harbor.zencluster.org/wilinger/bpmdatabase:0.1.8
          imagePullPolicy: Always
          args:
            - ./docker-entrypoint.sh
          envFrom:
            - secretRef:
                name: bpmdb-secrets-stg
      imagePullSecrets:
        - name: regcred