apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bpmdb

resources:
  - sealed-secrets/sealed-secret-regcred.yaml
  - sealed-secrets/sealed-bpmdb-doppler-token.yaml
  - sealed-secrets/doppler-secret-stg.yaml
  - pg-data-pvc.yaml
  - pg-deployment.yaml
  - pg-service.yaml
  - bpmdb-deployment.yaml
  - bpmdb-service.yaml
  - bpmdb-ingress.yaml