apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -terraform

patchStrategicMerge:
  - deployment_autoscaler.yaml
  - deployment_runner.yaml

# patches:
#   - patch: |-
#       apiVersion: actions.summerwind.dev/v1alpha1
#       kind: RunnerDeployment
#       metadata:
#         name: runner-deployment
#         namespace: cicd
#       spec:
#         template:
#           spec:
#             repository: wilinger/terraform-homelab
#   - patch: |-
#       apiVersion: actions.summerwind.dev/v1alpha1
#       kind: HorizontalRunnerAutoscaler
#       metadata:
#         name: autoscaler-ansible
#         namespace: cicd
#       spec:
#         scaleTargetRef:
#           name: runner-deployment-terraform
