apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -terraform

patches:
  - patch: |-
      apiVersion: actions.summerwind.dev/v1alpha1
      kind: RunnerDeployment
      metadata:
        name: runner-deployment-terraform
        namespace: cicd
      spec:
        template:
          spec:
            repository: wilinger/terraform-homelab
